version: "3.9"

services:
  postgres:
    image: "bitnami/postgresql"
    container_name: postgres
    restart: unless-stopped
    networks:
      - private-network
    ports:
      - '5432:5432'
    environment:
      POSTGRES_PASSWORD: "postgres"
      POSTGRES_DB: "identitydb"
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres -d identitydb" ]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s
    deploy:
      resources:
        limits:
          cpus: '1'
          memory: 1G
networks:
  private-network:
    driver: bridge