server:
  port: ${SERVER_PORT:8080}

jwt:
  privateKey: ${JWT_PRIVATE_KEY}
  publicKey: ${JWT_PUBLIC_KEY}

logging:
  level:
    ru.achernyavskiy0n.identity: ${LOG_LEVEL:INFO}

spring:
  profiles:
    active: ${SPRING_PROFILE:prod}
  main:
    banner-mode: off
  datasource:
    driver-class-name: org.postgresql.Driver
    url: ${DATASOURCE_URL:jdbc:postgresql://localhost:5432/news_db}
    username: ${DATASOURCE_USERNAME:postgres}
    password: ${DATASOURCE_PASSWORD:postgres}
  jpa:
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQL10Dialect
    open-in-view: false
    hibernate:
      ddl-auto: none
    properties:
      hibernate.types.print.banner: false

management:
  endpoint:
    health:
      probes.enabled: true
      livenessState.enabled: true
      readinessState.enabled: true
    prometheus:
      enabled: true
  endpoints:
    web:
      exposure:
        include: health,prometheus
      base-path: /
      path-mapping.health: health
  metrics:
    export:
      prometheus:
        enabled: true
    distribution:
      percentiles-histogram:
        "[http.server.requests]": true