server:
  port: ${SERVER_PORT:8080}

jwt:
  privateKey: ${JWT_PRIVATE_KEY}
  publicKey: ${JWT_PUBLIC_KEY}

management:
  endpoint:
    health:
      probes.enabled: true
      livenessState.enabled: true
      readinessState.enabled: true
    prometheus:
      enabled: true
  endpoints:
    web:
      exposure:
        include: health,prometheus
      base-path: /
      path-mapping.health: health
  metrics:
    export:
      prometheus:
        enabled: true
    distribution:
      percentiles-histogram:
        "[http.server.requests]": true

spring:
  kafka:
    producer:
      client-id: ${KAFKA_CLIENT_ID:identity}
      bootstrap-servers: ${KAFKA_BOOTSTRAP_SERVERS:localhost:9092}
      acks: all
      security.protocol: ${KAFKA_PROTOCOL:PLAINTEXT}
logging:
  level:
    org.apache.kafka.*: WARN

identity:
  transport:
    topics:
      billing:
        create: ${BILLING_CREATE_TOPIC:create}